export declare enum NodeNetworkConfigurationInterfaceIP {
  ENABLED = 'ENABLED',
  DHCP = 'DHCP',
  AUTO_DNS = 'AUTO_DNS',
  AUTO_GATEWAY = 'AUTO_GATEWAY',
  AUTO_ROUTES = 'AUTO_ROUTES',
  ADDRESS = 'ADDRESS',
  ADDRESS_IP = 'ADDRESS_IP',
  ADDRESS_PREFIX_LENGTH = 'ADDRESS_PREFIX_LENGTH',
  AUTO_ROUTE_METRIC = 'AUTO_ROUTE_METRIC',
}
