/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValue } from './V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValue';
import {
    V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueFromJSON,
    V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueFromJSONTyped,
    V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueToJSON,
} from './V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValue';
import type { V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfo } from './V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfo';
import {
    V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfoFromJSON,
    V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfoFromJSONTyped,
    V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfoToJSON,
} from './V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfo';

/**
 * NodeNetworkConfigurationEnactmentStatus defines the observed state of NodeNetworkConfigurationEnactment
 * @export
 * @interface V1alpha1NodeNetworkConfigurationEnactmentStatus
 */
export interface V1alpha1NodeNetworkConfigurationEnactmentStatus {
    /**
     * A cache containing the resolved captures after processing the capture at NNCP
     * @type {{ [key: string]: V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValue; }}
     * @memberof V1alpha1NodeNetworkConfigurationEnactmentStatus
     */
    capturedStates?: { [key: string]: V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValue; } | null;
    /**
     * 
     * @type {any}
     * @memberof V1alpha1NodeNetworkConfigurationEnactmentStatus
     */
    conditions?: any | null;
    /**
     * The desired state rendered for the enactment's node using the policy desiredState as template
     * @type {any}
     * @memberof V1alpha1NodeNetworkConfigurationEnactmentStatus
     */
    desiredState?: any | null;
    /**
     * 
     * @type {V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfo}
     * @memberof V1alpha1NodeNetworkConfigurationEnactmentStatus
     */
    desiredStateMetaInfo?: V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfo;
    /**
     * The generation from policy needed to check if an enactment condition status belongs to the same policy version
     * @type {any}
     * @memberof V1alpha1NodeNetworkConfigurationEnactmentStatus
     */
    policyGeneration?: any | null;
}

/**
 * Check if a given object implements the V1alpha1NodeNetworkConfigurationEnactmentStatus interface.
 */
export function instanceOfV1alpha1NodeNetworkConfigurationEnactmentStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1alpha1NodeNetworkConfigurationEnactmentStatusFromJSON(json: any): V1alpha1NodeNetworkConfigurationEnactmentStatus {
    return V1alpha1NodeNetworkConfigurationEnactmentStatusFromJSONTyped(json, false);
}

export function V1alpha1NodeNetworkConfigurationEnactmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1NodeNetworkConfigurationEnactmentStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capturedStates': !exists(json, 'capturedStates') ? undefined : json['capturedStates'],
        'conditions': !exists(json, 'conditions') ? undefined : json['conditions'],
        'desiredState': !exists(json, 'desiredState') ? undefined : json['desiredState'],
        'desiredStateMetaInfo': !exists(json, 'desiredStateMetaInfo') ? undefined : V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfoFromJSON(json['desiredStateMetaInfo']),
        'policyGeneration': !exists(json, 'policyGeneration') ? undefined : json['policyGeneration'],
    };
}

export function V1alpha1NodeNetworkConfigurationEnactmentStatusToJSON(value?: V1alpha1NodeNetworkConfigurationEnactmentStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capturedStates': value.capturedStates,
        'conditions': value.conditions,
        'desiredState': value.desiredState,
        'desiredStateMetaInfo': V1alpha1NodeNetworkConfigurationEnactmentStatusCapturedStatesValueMetaInfoToJSON(value.desiredStateMetaInfo),
        'policyGeneration': value.policyGeneration,
    };
}

